export const projects = [
    {
        title: "DUK",
        description:
            "A modern e-commerce platform for DUK Productions, featuring a sleek design with advanced product management and seamless user experience.",
        image: "./assets/duk.png",
        link: "https://dukprod.no/",
        featured: true,
        category: "E-Commerce",
        tech: ["React", "Node.js", "MongoDB", "Stripe", "Responsive Design"],
        github: "https://github.com/yourusername/duk-platform",
        liveDemo: "https://dukprod.no/",
    },
    {
        title: "Sentrum-Karate",
        description:
            "Professional website for Sentrum Karate Club with class scheduling, member portal, and dynamic content management system.",
        image: "./assets/sentrumkarate.png",
        link: "https://sentrum-karateklubb.no/",
        featured: false,
        category: "Business Website",
        tech: ["HTML5", "CSS3", "JavaScript", "PHP", "MySQL"],
        github: "https://github.com/yourusername/sentrum-karate",
        liveDemo: "https://sentrum-karateklubb.no/",
    },
    {
        title: "Billy",
        description:
            "Billy Pool website showcasing swimming pool services with modern design, contact forms, and service portfolio.",
        image: "./assets/billy.png",
        link: "https://billypool.no",
        featured: false,
        category: "Service Website",
        tech: ["HTML5", "CSS3", "JavaScript", "Contact Forms", "SEO"],
        github: "https://github.com/yourusername/billy-pool",
        liveDemo: "https://billypool.no",
    },
    {
        title: "Bohemian Dash",
        description:
            "A creative portfolio and showcase website with bohemian-inspired design, featuring smooth animations and artistic elements.",
        image: "./assets/bdash.png",
        link: "https://jonagull.github.io/bohemian-dash/",
        featured: false,
        category: "Creative Portfolio",
        tech: ["HTML5", "CSS3", "JavaScript", "Animations", "Creative Design"],
        github: "https://github.com/jonagull/bohemian-dash",
        liveDemo: "https://jonagull.github.io/bohemian-dash/",
    },
    {
        title: "Portfolio Website",
        description:
            "A modern, responsive portfolio website built with HTML, CSS, and JavaScript. Features elegant animations, glassmorphism effects, and a sophisticated design that showcases my work effectively.",
        image: "./assets/hero-image.png",
        link: "#",
        featured: false,
        category: "Portfolio",
        tech: [
            "HTML5",
            "CSS3",
            "JavaScript",
            "Responsive Design",
            "Animations",
        ],
        github: "https://github.com/yourusername/portfolio",
        liveDemo: "#",
    },
    {
        title: "Task Management App",
        description:
            "A productivity app for task management with real-time synchronization and offline capabilities.",
        image: "./assets/design.png",
        link: "#",
        featured: false,
        category: "Mobile App",
        tech: ["React Native", "Firebase", "Redux", "AsyncStorage"],
        github: "https://github.com/yourusername/task-app",
        liveDemo: "#",
    },
    {
        title: "Weather API",
        description:
            "A RESTful weather API service with caching, rate limiting, and real-time weather data integration.",
        image: "./assets/deploy.png",
        link: "#",
        featured: false,
        category: "Backend API",
        tech: ["Express.js", "Redis", "JWT", "Swagger"],
        github: "https://github.com/yourusername/weather-api",
        liveDemo: "#",
    },
    {
        title: "Analytics Dashboard",
        description:
            "An interactive analytics dashboard with real-time data visualization and customizable charts.",
        image: "./assets/programming-code.gif",
        link: "#",
        featured: false,
        category: "Data Visualization",
        tech: ["D3.js", "Vue.js", "WebSocket", "Chart.js"],
        github: "https://github.com/yourusername/analytics-dashboard",
        liveDemo: "#",
    },
];
